### ISSUE TITLE
'function' is recognized in all the wrong places

### ISSUE THREAD

**Issue by CodeFloh** [rscircus/fortress#4]
unwrapped_line.py, l. 291: This is not very safe. The word 'function' is even recognized as influencing the indentation when it's used inside a character string. Somehow, we need to check more carefully for this keyword.

**Comment by rscircus** [comment]
Duplicate of https://github.com/rscircus/fortress/issues/2 (sorry for the cnfsn, clicked the wrong tab, #5 is valid).

**Comment by CodeFloh** [comment]
Actually, recognizing 'function' anywhere **outside of strings** is fine. But we need to ignore strings. I will improve this to solve this issue, but I'm opening a separate issue concerning the indentation.
